# Generated by Django 4.2.1 on 2023-08-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dislyte_knockout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_esper',
            name='version',
            field=models.FloatField(default=0),
        ),
    ]
