# Generated by Django 4.2.1 on 2023-11-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dislyte_knockout', '0004_alter_player_esper_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_esper',
            name='team',
        ),
    ]
