# Generated by Django 4.2.1 on 2023-11-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dislyte_knockout', '0005_remove_player_esper_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_esper',
            name='team',
            field=models.IntegerField(default=0),
        ),
    ]
